### ISSUE TITLE
wgs converted to eov coordinates are not correct

### ISSUE THREAD

**Issue by KAMI911** [jswhit/pyproj#10]
Hi,
I try to create WGS84 to EOV converter. First I wanted to create an app that generate WGS grid coordinates to EOV coordinates.

EOV: http://spatialreference.org/ref/epsg/hd72-eov/

My code is here:
https://github.com/KAMI911/wgslas2eovlas/blob/master/gridcreator.py

I used python-pyproj                               1.8.9-1.1build2 packaged into Ubuntu/Linux Mint on 64 bit.

After I created file with EOV coordinates I tried to convert them back (and failed) to WGS with this tool:
http://pf-prg.hu/trafo/trafo-4.php?mod=0

Do you have idea what did i wrong? Or is this a bug in the software?

The output files are here:
http://ooo.itc.hu/wgseov/

Thank you in advance!

**Comment by micahcochran** [comment]
@KAMI911 Did you figure out the problem?

**Comment by KAMI911** [comment]
@micahcochran: I was able to figure out the problem. Thank you for your question.
