### ISSUE TITLE
failed install on macos Sierra: XYZ error

### ISSUE THREAD

**Issue by impactanalysts** [jswhit/pyproj#103]
I tried installing `pyproj 1.9.5.1` for Python 2.7, in a virtual environment on macos 10.12.2. The install failed, with errors referring to type names "XYZ" and "LPZ":

    error: unknown type name 'XYZ'; did you mean 'XY'?
            XYZ /* forward projection entry */
            ^~~
            XY
    /Users/Mike/anaconda/envs/geospatial_py2/include/projects.h:155:37: note: 'XY' declared here
    typedef struct { double x, y; }     XY;
                                        ^
    src/pj_fwd3d.c:7:10: error: unknown type name 'LPZ'; did you mean 'LP'?
    pj_fwd3d(LPZ lpz, PJ *P) {
             ^~~
             LP
    /Users/Mike/anaconda/envs/geospatial_py2/include/projects.h:156:37: note: 'LP' declared here
    typedef struct { double lam, phi; } LP;
                                        ^
    src/pj_fwd3d.c:8:2: error: unknown type name 'XYZ'; did you mean 'XY'?
            XYZ xyz;
            ^~~
            XY
    /Users/Mike/anaconda/envs/geospatial_py2/include/projects.h:155:37: note: 'XY' declared here
    typedef struct { double x, y; }     XY;
                                        ^
    src/pj_fwd3d.c:13:23: error: no member named 'z' in 'XY'
                    xyz.x = xyz.y = xyz.z = HUGE_VAL;
                                    ~~~ ^
    src/pj_fwd3d.c:29:24: error: no member named 'fwd3d' in 'struct PJconsts'
                    if (P->fwd3d != NULL)
                        ~  ^
    src/pj_fwd3d.c:31:18: error: no member named 'fwd3d' in 'struct PJconsts'
                        xyz = (*P->fwd3d)(lpz, P); /* project */
                                ~  ^
    src/pj_fwd3d.c:33:24: error: no member named 'z' in 'XY'
                            xyz.x = xyz.y = xyz.z = HUGE_VAL;
                                            ~~~ ^
    src/pj_fwd3d.c:43:41: error: no member named 'z' in 'XY'
                        xyz.x = xyz.y = xyz.z = HUGE_VAL;
                                        ~~~ ^
    8 errors generated.
    error: command 'gcc' failed with exit status 1
        ----------------------------------------
    Command "/Users/Mike/anaconda/envs/geospatial_py2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-build-75xxZg/pyproj/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-zi_Bo4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-build-75xxZg/pyproj/
      
I've attached the output of setup.py as a txt file: 
[pyproj install errors.txt](https://github.com/jswhit/pyproj/files/673435/pyproj.install.errors.txt)

Can you help?

Please let me know what you think. Any advice you can give toward getting pyproj installed on OSX would be much appreciated. I need it for other packages (i.e. georasters).

Mike

**Comment by micahcochran** [comment]
I don't really know what is going wrong.   Is your version of pip fairly recent (8 or 9)?  Does installing from the repository `$ pip install git+https://github.com/jswhit/pyproj.git` do anything different?

**Comment by impactanalysts** [comment]
I'm using pip 9.0.1. I tried installing `pyproj` from the repo (see below). `setup.py` said I need to install `Cython`.

    Collecting git+https://github.com/jswhit/pyproj.git
      Cloning https://github.com/jswhit/pyproj.git to /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build
      Complete output from command python setup.py egg_info:
      using bundled proj4..
      executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build/nad2bin lib/pyproj/data/alaska < datumgrid/alaska.lla
      Output Binary File Format: ctable2
      executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build/nad2bin lib/pyproj/data/conus < datumgrid/conus.lla
      Output Binary File Format: ctable2
      executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build/nad2bin lib/pyproj/data/FL < datumgrid/FL.lla
      Output Binary File Format: ctable2
      executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build/nad2bin lib/pyproj/data/hawaii < datumgrid/hawaii.lla
      Output Binary File Format: ctable2
      executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build/nad2bin lib/pyproj/data/MD < datumgrid/MD.lla
      Output Binary File Format: ctable2
      executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build/nad2bin lib/pyproj/data/null < datumgrid/null.lla
      Output Binary File Format: ctable2
      executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build/nad2bin lib/pyproj/data/prvi < datumgrid/prvi.lla
      Output Binary File Format: ctable2
      executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build/nad2bin lib/pyproj/data/stgeorge < datumgrid/stgeorge.lla
      Output Binary File Format: ctable2
      executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build/nad2bin lib/pyproj/data/stlrnc < datumgrid/stlrnc.lla
      Output Binary File Format: ctable2
      executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build/nad2bin lib/pyproj/data/stpaul < datumgrid/stpaul.lla
      Output Binary File Format: ctable2
      executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build/nad2bin lib/pyproj/data/TN < datumgrid/TN.lla
      Output Binary File Format: ctable2
      executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build/nad2bin lib/pyproj/data/WI < datumgrid/WI.lla
      Output Binary File Format: ctable2
      executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build/nad2bin lib/pyproj/data/WO < datumgrid/WO.lla
      Output Binary File Format: ctable2
    
    
      _proj.c does not exist in a repository copy.
      ImportError: Cython must be installed in order to generate _proj.c
        	to install Cython run `pip install cython`
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-Wd1YX5-build/

So I installed `Cython 0.25.2`. Next I tried again to install `pyproj` from the repo, but it failed with this error:

    error: use of undeclared identifier 'M_HALFPI'

What should I try next? 

Full output of `setup.py`:

    Collecting git+https://github.com/jswhit/pyproj.git
    Cloning https://github.com/jswhit/pyproj.git to /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build
    Installing collected packages: pyproj
    Running setup.py install for pyproj ... error
    Complete output from command /Users/Mike/anaconda/envs/geospatial_py2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-abI8D2-record/install-record.txt --single-version-externally-managed --compile:
    using bundled proj4..
    executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/nad2bin lib/pyproj/data/alaska < datumgrid/alaska.lla
    Output Binary File Format: ctable2
    executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/nad2bin lib/pyproj/data/conus < datumgrid/conus.lla
    Output Binary File Format: ctable2
    executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/nad2bin lib/pyproj/data/FL < datumgrid/FL.lla
    Output Binary File Format: ctable2
    executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/nad2bin lib/pyproj/data/hawaii < datumgrid/hawaii.lla
    Output Binary File Format: ctable2
    executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/nad2bin lib/pyproj/data/MD < datumgrid/MD.lla
    Output Binary File Format: ctable2
    executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/nad2bin lib/pyproj/data/null < datumgrid/null.lla
    Output Binary File Format: ctable2
    executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/nad2bin lib/pyproj/data/prvi < datumgrid/prvi.lla
    Output Binary File Format: ctable2
    executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/nad2bin lib/pyproj/data/stgeorge < datumgrid/stgeorge.lla
    Output Binary File Format: ctable2
    executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/nad2bin lib/pyproj/data/stlrnc < datumgrid/stlrnc.lla
    Output Binary File Format: ctable2
    executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/nad2bin lib/pyproj/data/stpaul < datumgrid/stpaul.lla
    Output Binary File Format: ctable2
    executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/nad2bin lib/pyproj/data/TN < datumgrid/TN.lla
    Output Binary File Format: ctable2
    executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/nad2bin lib/pyproj/data/WI < datumgrid/WI.lla
    Output Binary File Format: ctable2
    executing /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/nad2bin lib/pyproj/data/WO < datumgrid/WO.lla
    Output Binary File Format: ctable2
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-2.7
    creating build/lib.macosx-10.7-x86_64-2.7/pyproj
    copying lib/pyproj/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/pyproj
    copying lib/pyproj/datadir.py -> build/lib.macosx-10.7-x86_64-2.7/pyproj
    creating build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/alaska -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/conus -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/epsg -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/esri -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/esri.extra -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/FL -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/GL27 -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/hawaii -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/IGNF -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/MD -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/nad.lst -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/nad27 -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/nad83 -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/ntf_r93.gsb -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/ntv1_can.dat -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/ntv2_out.dist -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/null -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/nzgd2kgrid0005.gsb -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/other.extra -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/pj_out27.dist -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/pj_out83.dist -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/proj_def.dat -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/proj_outIGNF.dist -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/prvi -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/README -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/stgeorge -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/stlrnc -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/stpaul -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/td_out.dist -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/test27 -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/test83 -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/testdatumfile -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/testIGNF -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/testntv2 -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/testvarious -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/TN -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/tv_out.dist -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/WI -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/WO -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    copying lib/pyproj/data/world -> build/lib.macosx-10.7-x86_64-2.7/pyproj/data
    running build_ext
    building 'pyproj._proj' extension
    creating build/temp.macosx-10.7-x86_64-2.7
    creating build/temp.macosx-10.7-x86_64-2.7/src
    gcc -fno-strict-aliasing -I/Users/Mike/anaconda/envs/geospatial_py2/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -Isrc -I/Users/Mike/anaconda/envs/geospatial_py2/include/python2.7 -c src/aasincos.c -o build/temp.macosx-10.7-x86_64-2.7/src/aasincos.o
    src/aasincos.c:14:21: error: use of undeclared identifier 'M_HALFPI'
                    return (v < 0. ? -M_HALFPI : M_HALFPI);
                                      ^
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
    Command "/Users/Mike/anaconda/envs/geospatial_py2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-abI8D2-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/n1/4zz_xfnj29j4hmm3x505b39c0000gp/T/pip-bRBChU-build/

**Comment by impactanalysts** [comment]
The problem seems to stem from missing dependencies (for example, my venv was missing `scipy`,  `matplotlib`, and `fiona`, even though `gdal` and `ogr` are installed). Also, with `matplotlib` on `macos`, there is a separate issue with GUI frameworks and virtual environments. Apparently `pip` can't install GUI frameworks. See [Working with Matplotlib in Virtual environments](http://matplotlib.org/faq/virtualenv_faq.html).

But I'm still running into the "XYZ" issue from `pyproj`. During the install of `fiona`, `setup.py` also tried again to install `pyproj`, which I guess `fiona` is dependent on? The install failed with the same error about `unknown type name 'XYZ'; did you mean 'XY'?`

So I'm still stuck.

**Comment by micahcochran** [comment]
Your GCC compiler seems to be acting a little differently.

`matplotlib`, `fiona`, and `pyproj` are all harder packages to install due to C library dependencies.  `Fiona` does not require `pyproj`.  (`Fiona` has one example that uses `pyproj`, but that doesn't seem that it is ever ran by unit testing.)

In my experience, I've had are harder time--on Windows--installing `Fiona` than `pyproj`.  On macos x, I would hope that `gdal-config` would make installing `Fiona` much easier.  `Fiona` does not use the python `gdal` package, but it does use the C GDAL library and you may have to tell it where it is installed (GDAL is a requirement for `Fiona`).

If you want to go the binary route for installation, you might try [conda](https://repo.continuum.io/pkgs/).  I really can't help you with that.

**Comment by impactanalysts** [comment]
Thanks. I will try the `conda` route. Will let you know how that goes. There are so many ways to install libraries on OSX -- `pip, conda, brew, easy_install, macports` -- it's hard to know which one to use. Also, since `conda` is both a virtual environment creator and package installer, I'm not sure if I should ONLY use `conda` in venvs created by `conda`, or if it's okay to also use `pip` in a `conda` venv?

**Comment by ozak** [comment]
I got a similar error when trying to upgrade to ``pyproj-1.9.5.1`` using ``pip install --upgrade pyproj``. My ``homebrew Python`` installation works perfectly fine, but trying to upgrade this package gives

    pip install --upgrade pyproj==1.9.5
    Collecting pyproj==1.9.5
      Downloading pyproj-1.9.5.tar.gz (2.7MB)
        100% |████████████████████████████████| 2.7MB 401kB/s
        Complete output from command python setup.py egg_info:
        nad2bin.c:352:60: error: use of undeclared identifier 'PI'
                            row_buf[i*4+0] = cvs->phi * (3600.0 / (PI/180.0));
                                                                   ^
        nad2bin.c:353:60: error: use of undeclared identifier 'PI'
                            row_buf[i*4+1] = cvs->lam * (3600.0 / (PI/180.0));
                                                                   ^
        2 errors generated.
        using bundled proj4..
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/private/var/folders/74/f8jv43x13mn4r07rw06crj4w0000gp/T/pip-build-nHgxT4/pyproj/setup.py", line 72, in <module>
            objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
          File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/ccompiler.py", line 574, in compile
            self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
          File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile
            raise CompileError, msg
        distutils.errors.CompileError: command 'clang' failed with exit status 1
    
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/74/f8jv43x13mn4r07rw06crj4w0000gp/T/pip-build-nHgxT4/pyproj/

But, I am able to upgrade using ``pip install git+https://github.com/jswhit/pyproj.git``. So perhaps the version uploaded to ``PyPi`` is corrupted or something?

**Comment by micahcochran** [comment]
> But, I am able to upgrade using ``pip install git+https://github.com/jswhit/pyproj.git``. So perhaps the version uploaded to ``PyPi`` is corrupted or something?

@ozak   The answer is  a little more complicated than pyproj 1.9.5.1 being corrupt.  pyproj is currently not tested OSX compatibility.  Travis-CI can do OSX testing, but I've never tried to set it up.

nad2bin.c is code provided by the proj4 C library which compiles into an executable binary.   nad2bin executable converts datum correction files from an ASCII format (*.lla files) to a binary version.   proj4 only uses the binary version.  (proj4 release 4.9.3 using the newest datums are all distributed in binary format. I would eventually like to get rid nad2bin step.)

In version proj4 version 4.9.3, math constants were changed to be more standardized across the entire project.  So, PI was changed to M_PI, which is the defacto standard for C math constants.

The pyproj repository (AKA `pip install git+https://github.com/jswhit/pyproj.git`) has proj4 version 4.9.3 release in it.

pyproj version 1.9.5.1 includes a repository version of proj4 a few months before 4.9.3 was released, and--I assume--before said math constant update.

Ubuntu is tested with gcc, not clang.  A new release is probably not a bad idea, it has been about a year since 1.9.5.1, and there are a few new features in the repository.

**Comment by ozak** [comment]
So you mean it's some kind of dependency issue? I've seen that before also in other packages... Used to be solved by using the ``--no- wheels`` option so that it would compile the source code when installing. Wonder if that would solve the issue here also?

**Comment by micahcochran** [comment]
@ozak 
Sorta.  pyproj requires the C library proj.4, and proj.4 needs datum correction files to give the best coordinates.  Those datum correction files give better coordinates due better measurements methods and continental drift.

I am a little doubtful that `--no-wheels` will be a solution. 

Anyone can install the proj.4 library, and provide a path to the directory for pyproj's installation.  However, you must use the same compiler version as the compiler that compiled that version of python.  There is a little bit of Cython code that has to be compiled to C.

**Comment by Juanlu001** [comment]
+1 for a release that fixes the OS X installation issues while we wait for binary wheels as well (#130).
