### ISSUE TITLE
Installation pyproj in Python 3.6

### ISSUE THREAD

**Issue by Rashid-S** [jswhit/pyproj#116]
In PyCharm I try to execute the command  'pip3 install pyproj'.  As a result, I get this: 
![image](https://cloud.githubusercontent.com/assets/22569886/25815423/21dc24ec-3442-11e7-8dae-7cd6f14e42b0.png)

**Comment by Rashid-S** [comment]
Help me

**Comment by micahcochran** [comment]
You need to install Microsoft Visual C++ 14.0 in order to compile the C code for pyproj.   Follow the URL in the screenshot.

**Comment by Rashid-S** [comment]
Many thanks. Everything worked out

**Comment by micahcochran** [comment]
Very good. Closing the issue.
