### ISSUE TITLE
Installation compile error

### ISSUE THREAD

**Issue by byezy** [jswhit/pyproj#121]
Hi, I am encountering this compilation error when trying to install pyproj (geopandas support) into a python 3 virtual environment under SUSE:

OS:
byed@irsdev01:~> lsb_release -a
LSB Version:    core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID: SUSE LINUX
Description:    SUSE Linux Enterprise Server 11 (x86_64)
Release:        11
Codename:       n/a

ERROR:
(venv36) byed@irsdev01:/mnt/scratch/byed> pip install -U geopandas
Collecting geopandas
  Using cached geopandas-0.2.1-py2.py3-none-any.whl
Collecting pyproj (from geopandas)
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    In file included from src/projects.h:292:0,
                     from nad2bin.c:7:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from nad2bin.c:7:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    nad2bin.c:46:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     static void Usage()
                 ^
    nad2bin.c: In function ‘main’:
    nad2bin.c:362:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                         != 4 * ct.lim.lam )
                         ^
    gcc: error trying to exec 'as': execvp: No such file or directory
    Traceback (most recent call last):
      File "/home/byed/python3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/home/byed/python3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/home/byed/python3/lib/python3.6/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/home/byed/python3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command '/mnt/appsource/gcc/gcc-5.1.0/bin/gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-02ci571y/pyproj/setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "/home/byed/python3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/home/byed/python3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command '/mnt/appsource/gcc/gcc-5.1.0/bin/gcc' failed with exit status 1

    ----------------------------------------

**Comment by micahcochran** [comment]
Travis currently doesn't currently test Python 3.6.  A pull request would be welcome.

Perhaps `distutils` might is not working under Python 3.6. Is `setuptools` installed?

**Comment by byezy** [comment]
Pyproj installed today (pipping geopandas), sorry I don't know what might have happened but all good now.
...
Requirement already satisfied: munch in ./venv36/lib/python3.6/site-packages (from fiona->geopandas)
Requirement already satisfied: cligj in ./venv36/lib/python3.6/site-packages (from fiona->geopandas)
Requirement already satisfied: click-plugins in ./venv36/lib/python3.6/site-packages (from fiona->geopandas)
Requirement already satisfied: six in ./venv36/lib/python3.6/site-packages (from fiona->geopandas)
Requirement already satisfied: numpy>=1.7.0 in ./venv36/lib/python3.6/site-packages (from pandas->geopandas)
Requirement already satisfied: pytz>=2011k in ./venv36/lib/python3.6/site-packages (from pandas->geopandas)
Requirement already satisfied: python-dateutil>=2 in ./venv36/lib/python3.6/site-packages (from pandas->geopandas)
Collecting cycler>=0.10 (from matplotlib->descartes->geopandas)
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in ./venv36/lib/python3.6/site-packages (from matplotlib->descartes->geopandas)
Requirement already satisfied: click>=4.0 in ./venv36/lib/python3.6/site-packages (from cligj->fiona->geopandas)
Installing collected packages: cycler, matplotlib, descartes, pyproj, geopandas
  Running setup.py install for pyproj ... done
Successfully installed cycler-0.10.0 descartes-1.1.0 geopandas-0.2.1 matplotlib-2.0.2 pyproj-1.9.5.1
(venv36) byed@irsdev01:~>
