### ISSUE TITLE
failed to install on fedora: gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory

### ISSUE THREAD

**Issue by rbolgaryn** [jswhit/pyproj#123]
While installing using pip on fedora 26, the following error occurred:

Collecting pyproj
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gKdvhx/pyproj/setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "/usr/lib64/python2.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib64/python2.7/distutils/unixccompiler.py", line 134, in _compile
        raise CompileError, msg
    distutils.errors.CompileError: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gKdvhx/pyproj/

**Comment by jdkloe** [comment]
I packaged pyproj for Fedora, so you could try to install it through dnf of PackageManager. Would that be an option for you?
Your error seems to be caused by a missing package. The missing file is part of redhat-rpm-config-63-1.fc26.noarch, so installation of that package also might solve your problem.

**Comment by jdkloe** [comment]
Did my suggestions work for you?

**Comment by korantu** [comment]
dnf install redhat-rpm-config resolved similar issue for me.

**Comment by jdkloe** [comment]
thanks for confirming. I propose to close this issue.

**Comment by korantu** [comment]
Ya, I dont think you can resolve this dependency from setup.py or something. and it is specific to fedora, so maybe document it somewhere and close would make sense...

**Comment by jdkloe** [comment]
@jswhit could you close this issue?

**Comment by rbolgaryn** [comment]
hi, thanks for your comment and the solution
