### ISSUE TITLE
Question: How do you calculate the latitude and longitude for every pixel in GOES-16 data?

### ISSUE THREAD

**Issue by blaylockbk** [jswhit/pyproj#124]
GOES-16 is a geostationary satellite and the data is given in a geostationary projection. I'm ultimately trying to get the latitude and longitude of each pixel in GOES-16 satellite data, and then reproject the data on other maps with Lambert Conformal Conic or Equidistant Cylindrical projections.

<img src='https://user-images.githubusercontent.com/6249613/30494901-24977b20-9a07-11e7-9115-486e231ac57f.PNG' width='50%'>

After reading the docs for pyproj and proj, I'm still unsure how to calculate latitude and longitude for the geostationary projection. Still, I'm hopefully pyproj can provide the solution.

Projection data I can glean from the GOES-16 file include:

    long_name: GOES-R ABI fixed grid projection
    grid_mapping_name: geostationary
    perspective_point_height: 35786023.0
    semi_major_axis: 6378137.0
    semi_minor_axis: 6356752.31414
    inverse_flattening: 298.2572221
    latitude_of_projection_origin: 0.0
    longitude_of_projection_origin: -89.5
    sweep_angle_axis: x

I am also provided with the x and y grid projection coordinates in scan angle radians. These vectors have lengths of 54240.

    x_scan_angle = array([-0.15184399, -0.151788  , -0.151732  , ...,  0.151732  ,  0.151788  ,  0.15184399], type=float32)
    y_scan_angle = array([ 0.15184399,  0.151788  ,  0.151732  , ..., -0.151732  , -0.151788  , -0.15184399], type=float32)

I first started by setting the projection object:

    from pyproj import Proj
    p = Proj(proj='geos', h='35786023.0', lon_0='-89.5', sweep='x')

Following the simple formula for the projection coordinate, proj_coor = scan_angle_radians * height (http://proj4.org/projections/geos.html), I get:

    X_proj_coor = array([-5433893., -5431889., -5429885., ...,  5429885.,  5431889., 5433893.], type=float32)  
    Y_proj_coor = array([-5433893., -5431889., -5429885., ...,  5429885.,  5431889., 5433893.], type=float32)
But performing an inverse projection, I don't get valid latitude or longitudes returned. It only returns an array of zeros.

    lons, lats = p(X_proj_coor, Y_proj_coo, inverse=True)

Also, doing a reverse projection doesn't return a 2D grid of all the pixels, only values along the axes. Is `np.meshgrid(X_proj_coor, Y_proj_coor)` the right method for creating a 2D grid of latitude and longitude for every pixel in the data?

Any help is much appreciated.

**Comment by micahcochran** [comment]
[Rasterio](https://github.com/mapbox/rasterio) might be a better fit if you are trying to do raster reprojection.  (You may be able to skip the lat/long step.)  If/once the data is georeferenced, a many GIS tools can do raster reprojection (GDAL, ArcGIS Desktop, QGIS).

I haven't use satellite data in GIS in years, so I might be wrong.

Do you have a link to the metadata for GEOS-16?

**Comment by blaylockbk** [comment]
I managed to get things working with `pyproj` for the CONUS domain (just had to read some of the documentation for `proj`). Hopefully some else may find this useful...
https://github.com/blaylockbk/pyBKB_v2/blob/master/BB_goes16/mapping_GOES16_data.ipynb

Converted this...
![image](https://user-images.githubusercontent.com/6249613/30654610-a3a23f4e-9deb-11e7-80f3-e1c62dcd1065.png)

to this...
![image](https://user-images.githubusercontent.com/6249613/30654629-b2773d1c-9deb-11e7-8d4d-db1e2243d102.png)

For the full disk GOES-16 data, like the image shown in the question above, there are some issues with the black space around the globe when trying to do an inverse transformation. I think that needs to be masked out.

**Comment by gc13141112** [comment]
Hi, I use the pyproj to transform Himawari-8 data, then the result present a (1e+30, 1e+30)

**Comment by blaylockbk** [comment]
Not sure why you are getting zeros for all the points. Would require some debugging

**Comment by SantiTian** [comment]
Hi, would you mind tell a little more about x_scan_angle and y_scan_angle? Do they have the same values everywhere?

**Comment by blaylockbk** [comment]
The values are not the same everywhere. Scan angle is the angle of the scan from the satellite nadir. The satellite looking straight down would have a value of zero in x and y, and scan angle increases the further away the pixel is from nadir. See more documentation here: [http://proj4.org/projections/geos.html](http://proj4.org/projections/geos.html)

**Comment by MasoudGhr** [comment]
Hi, I am going to use the GOES-16 L2 AOD product in my research and appreciate it if you can answer my question regarding this product.
My research is during the 2019-2020 period over the CONUS, and I am going to convert the "GOES fixed grid projection coordinates" to the geographic coordinate system (lat/lon).
My question is that if the coordinate of a specific ground station (e.g., in New York City) is always fixed in the "GOES fixed grid projection coordinates," or it will change in different AOD images over time?
I'm asking this because if the coordinate of a specific ground station is always fixed in all AOD images during 2019-2020, I can implement the coordinate conversion process only for one image and use the converted coordinates for all AOD images in 2019-2020.
Please note that all the downloaded L2 AOD images are from GOES-16 over the CONUS (2-km spatial resolution).

Thanks in advance

**Comment by blaylockbk** [comment]
As far as I can tell, the fixed grid is in fact steady and doesn't change. The level 2 processing makes sure of that.

**Comment by MasoudGhr** [comment]
Thank you @blaylockbk .

**Comment by MasoudGhr** [comment]
Hi Brian,
Thank you for your kind reply.
Best regards,Masoud




    On Friday, March 26, 2021, 10:26:42 AM CDT, Brian Blaylock ***@***.***> wrote:  
 
 


As far as I can tell, the fixed grid is in fact steady and doesn't change. The level 2 processing makes sure of that.

**Comment by joyphysi** [comment]
Is there any Matlab code to find the lat and long values from the X and Y matrix?

**Comment by snowman2** [comment]
Related: https://gis.stackexchange.com/questions/345650/how-do-i-add-projection-to-this-netcdf-file-satellite
