### ISSUE TITLE
Issues converting NAD83 to New York State Plane

### ISSUE THREAD

**Issue by amkaris** [jswhit/pyproj#126]
`NAD83_LI = pyproj.Proj("+init=EPSG:32118")
NYS_LIZ = pyproj.Proj("+init=ESRI:102718")

def coord_transform(df):
    x = pd.Series()
    y = pd.Series()
    for idx, val in enumerate(df['Latitude']):
        x1, y1 = pyproj.transform(NAD83_LI, NYS_LIZ, df['Longitude'][idx], df['Latitude'][idx])
        x.set_value(idx, x1)
        y.set_value(idx, y1)
    df['x'] = x
    df['y'] = y
    return df
    
subways_loc_trans = coord_transform(subways_loc)

print(subways_loc_trans.head(1))`
    Latitude  Longitude          x          y
0  40.849169 -73.868356 -73.868356  40.849169

Why is it not transforming the NAD83 coordinates to NAD 1983 StatePlane New York Long Island FIPS 3104 Feet?

**Comment by micahcochran** [comment]
What do you mean by "NAD83 coordinates"?  NAD83 itself is a datum. Perhaps you mean NAD83 using latitude and longitude.

The most common latitude and longitude representation in WGS84 is known as EPSG 4326 (probably the most popular coordinate representation).  The equivalent datum for North American Datum 1983 with Latitude/Longitude is EPSG 4269. 

EPSG 4326 would also work, but it will probably be a off a bit.

**Comment by amkaris** [comment]
@micahcochran Yeah you're right. I realized that the person I asked didn't give me the projection, just the datum.

I will use WGS84 projection!
