### ISSUE TITLE
is it possible to make a new release with current master?

### ISSUE THREAD

**Issue by arielzn** [jswhit/pyproj#132]
Hi,

I would like to create a package for this to be built with EasyBuild (https://github.com/easybuilders/easybuild), that will help to many to install it building from source easily.
But I need features that were included after the latest 1.9.5.1 release 2 years ago (like compatibility with PROJ 4.9.3).
Is it  possible for you to create a newer release with all the commits included so far in master?
I need a .tar.gz with a fixed checksum to create a reproducible build with the mentioned tool.

Thanks

**Comment by thinrope** [comment]
Another benefit will be the [added python 3.6 support](https://github.com/jswhit/pyproj/commit/5335b371287ec91a53615d47bf6cdd451ae537dc)...

**Comment by AmitAronovitch** [comment]
Please note that a new release should help with other active issues - in particular
https://github.com/jswhit/pyproj/issues/136 (new release will cause a new _proj.c to be packaged, which should enable py3.7 support).

And, making `pip install` work would probably make the need for binary wheels ( https://github.com/jswhit/pyproj/issues/130 ) less urgent.

@jswhit please let us know if there is any issue we can help with that is blocking the next release to pypi

**Comment by jswhit** [comment]
New release is up on pypi now.
