### ISSUE TITLE
epsg:3404 and 3358 project to meters, but they should be US Survey Feet

### ISSUE THREAD

**Issue by PaulSchrum** [jswhit/pyproj#135]
I have lat/long coordinates in Wake County, North Carolina in a kml file. I am using pyproj to project them to either epsg:3404 or 3358. (I have tried both.) The coordinates are converted to meters instead of US Survey Feet as indicated at http://spatialreference.org/ref/epsg/3404/ .

I am comparing the shapefile that I created to a known good shapefile of North Carolina 
http://data.nconemap.gov/geoportal/catalog/search/resource/details.page?uuid=%7B2722196A-DF43-4734-BD54-91A0856F045C%7D

and plotting both with http://mapshaper.org/

In order to get correct coordinates, I have to check for 3404 or 3358 in the epsg string, and if either is present, multiply the values by the US Survey Foot conversion factor from Meters. Only then do they plot correctly.

**Comment by micahcochran** [comment]
duplicate of #67

**Comment by PaulSchrum** [comment]
Thank you, and sorry for the duplicate.
Also, thank your for this awesome free module.
