### ISSUE TITLE
Support for Python 3.7

### ISSUE THREAD

**Issue by AleksMat** [jswhit/pyproj#136]
Hi,

now that Python 3.7 is officially the latest stable version, do you have any plans to support it?

At the moment `pyproj` is raising an error when I try to install it locally for Python 3.7.0 (using pip 10.0.1 and Linux Ubuntu). I get the same error as when I try to run Travis CI for my package which has `pyproj` as a dependency: [error message](https://travis-ci.org/sentinel-hub/sentinelhub-py/jobs/401845158)

**Comment by AleksMat** [comment]
Thanks for adding Travis tests. I see that installing the package from GitHub repo works fine for me too. It is the latest version available on PyPI that is outdated and is raising an error during installation for Python 3.7.

Could someone also make a new release and upload it to PyPI?

**Comment by micahcochran** [comment]
> Thanks for adding Travis tests. I see that installing the package from GitHub repo works fine for me too. It is the latest version available on PyPI that is outdated and is raising an error during installation for Python 3.7.

I suspect it is an issue with the C file generated by Cython.  The version requirements for Cython probably need to be updated in requirements-dev.txt... I guess Cython 0.28 should be the minimum to support Python 3.7.  ([Cython Changelog](http://docs.cython.org/en/latest/src/changes.html))

**Comment by AleksMat** [comment]
When I use the latest Cython version `0.28.3` installing from PyPI still doesn't work, but from GitHub it does. So the reason must be some of the improvements that have been done since the latest release to PyPI (6th January 2016) until now.

**Comment by micahcochran** [comment]
It looks like 0.28.4 was (released last week)[https://github.com/cython/cython/releases], so I guess that should now be the minimum Cython version.

**Comment by valgur** [comment]
> When I use the latest Cython version 0.28.3 installing pyproj from PyPI still doesn't work, but from GitHub it does. So the reason must be some of the improvements that have been done since the latest release to PyPI (6th January 2016) until now.

The reason why the PyPI release does not work but installing from Git (with `pip install git+https://github.com/jswhit/pyproj.git`, for example) does is essentially the same that @micahcochran already mentioned: the `_proj.pyx` needs a recompilation to `_proj.c` with a newer version of Cython. The difference between the PyPI release and the Git repo is that the `_proj.c` file is not included in the latter, which triggers a recompilation of the `_proj.pyx` file and solves the problem, provided that a correct version of Cython is installed.

**Comment by aleksanb** [comment]
Is this releasable now?
I've been trying to get a dependency of our project to use the master of this library, but pipenv really doesn't like git urls for transitive dependencies, so I think I'm stuck waiting for a new release on pypi.

**Comment by aleksanb** [comment]
Anything we can help with to build and release a new version of this library?

**Comment by milieu** [comment]
Thank you @valgur for what you said above - it gave me inspiration on how to get this repo working with pipenv! 🎉 

```
pipenv install cython
pipenv install git+https://github.com/jswhit/pyproj.git#egg=pyproj
```

**Comment by Rockhound-NC** [comment]
Try a pre-compiled wheel. After struggling with install via pip, I downloaded the 37 whl file at following URL and pointed my pip install to that file. voila!

https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj

**Comment by dongli** [comment]
PyPI release still does not work.

**Comment by heitorPB** [comment]
`pip install pyproj` fails with `error: command 'gcc' failed with exit status 1`

> The reason why the PyPI release does not work but installing from Git (with `pip install git+https://github.com/jswhit/pyproj.git`, for example) does is essentially the same that @micahcochran already mentioned: the `_proj.pyx` needs a recompilation to `_proj.c` with a newer version of Cython. The difference between the PyPI release and the Git repo is that the `_proj.c` file is not included in the latter, which triggers a recompilation of the `_proj.pyx` file and solves the problem, provided that a correct version of Cython is installed.
  
@valgur , is it possible to force `pip` to recompile the `_proj.c`? Or to update the PyPi?

**Comment by ngoldbaum** [comment]
Cutting a new release would really help this!

**Comment by rgommers** [comment]
> @valgur , is it possible to force pip to recompile the `_proj.c`? Or to update the PyPi?

No, the code in `setup.py` prevents that (as it should). 

@micahcochran @jswhit a new release compiled with a new enough Cython is the only way to fix this for people. The last release on PyPI is 1.9.5.1, from Jan 2016. Could you please comment on whether you have any plans for a new release? This package seems maintained, and is an important dependency for large parts of the spatial stack (e.g. `geopandas`).  If no new release is planned, that would be good to know - then alternative plans can be made for Python 3.7 (or we can tell users "only conda works").

**Comment by mayanksuman** [comment]
Installation of geopandas and pyresample fail due to pyproj for python 3.7. 

The last release on PyPi is more 2yrs old. Please consider releasing the new version on PyPi, which will help other libraries based on pyproj.

**Comment by kev1807** [comment]
Hi there, 

As I am fairly new to Python (which I used some years back ... however, about 7 years without any Python) I'm not quite sure, whether this is the same problem: 
https://pastebin.com/zUjm6AL2

I am using either PyCharm or Spyder, have only setup anaconda3 and installed pycharm. So no confusion with python installation(s) 
Any help here or move it somewhere else?

**Comment by mayanksuman** [comment]
> [](https://pastebin.com/zUjm6AL2)
> 
> I am using either PyCharm or Spyder, have only setup anaconda3 and installed pycharm. So no confusion with python installation(s)
> Any help here or move it somewhere else?

Please read the error message. You need to install MS Visual C++ 14.0 to compile pyproj.

**Comment by NotSoShaby** [comment]
After many many tries to make this work I ended up downgrading my python to 3.6.1 for this to work. I really think that its sad that because of one package I had to downgrade my python version (I couldnt spend any more time on it). So it would be nice if this was fixed. 

I use macos Mojave and pipenv to install (although @milieu comment seemed to help people it did not work for me).

**Comment by rgommers** [comment]
@kev1807 if you're using Anaconda then install from conda-forge: `conda install -c conda-forge pyproj`. It also has Python 3.7. 

In general, using conda and installing the geopython stack from conda-forge is anyway by far the best option. There are way too many other things that are super hard to do if you try to use pip/pipenv only (e.g. GDAL).

**Comment by rgommers** [comment]
> @micahcochran @jswhit a new release compiled with a new enough Cython is the only way to fix this for people. The last release on PyPI is 1.9.5.1, from Jan 2016. Could you please comment on whether you have any plans for a new release? This package seems maintained, and is an important dependency for large parts of the spatial stack (e.g. geopandas). If no new release is planned, that would be good to know - then alternative plans can be made for Python 3.7 (or we can tell users "only conda works").

I have checked whether it's possible to ask PyPI maintainers for permission to upload new wheels. There is now a process for that, [PEP 514](https://www.python.org/dev/peps/pep-0541/). It requires the project to be considered abandoned, which means no new commits in this repo for at least a year. Since there are new commits (even a Python 3.7 CI related one from last month), that won't work. We'll just all have to wait.

**Comment by jswhit** [comment]
I can upload a new release on pypi today or tomorrow, if someone can create a release tag.

**Comment by jswhit** [comment]
Just created a pull request (pull request #154) for a new release

**Comment by rgommers** [comment]
Awesome, thanks @jswhit

**Comment by jswhit** [comment]
New source release (1.9.6) on pypi.  I will try to update the included proj4 source next, and then hopefully create a new release that includes binary wheels.
