### ISSUE TITLE
Install pyproj 1.9.6 --> link.exe' failed with exit status 1169

### ISSUE THREAD

**Issue by TobiasDK** [jswhit/pyproj#159]
Hi, I get this error with Windows 10, 64 bit, Anaconda Prompt, Python 3.7.2, pyproj 1.9.6 Please advise.
pip install pyproj -->

``
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1169
``

**Comment by jswhit** [comment]
please try again - there are windows binary wheels on pypi now.
