### ISSUE TITLE
Cite pyproj using a DOI

### ISSUE THREAD

**Issue by amabdallah** [jswhit/pyproj#165]
Hi,

Thanks for the very useful tool. Would you please create a DOI for this repository so I can cite it appropriately? Peer-reviewed papers/journals love DOIs :)

Here is how you could easily do it with Zonedo in case you're not aware of it
https://guides.github.com/activities/citable-code/

Thank you so much for the handy tool
Adel

**Comment by jswhit** [comment]
OK, I enabled the repo in Zonedo.  We should have a DOI for the upcoming 2.0.0. release.

**Comment by amabdallah** [comment]
Could you add the DOI badge to the ReadME?

**Comment by jswhit** [comment]
Zenodo did not recognize the 2.0.x releases - trying to figure out why.  Have you used Zenodo before?

**Comment by jswhit** [comment]
OK, I figured it out.  The github release has to be named `vX.Y.Z`, not `vX.Y.Zrel`.  The DOI badge for the upcoming 2.0.2 release is at https://github.com/jswhit/pyproj/tree/v2.0.2rel (will show up at https://github.com/jswhit/pyproj when I merge the release branch into master).
