### ISSUE TITLE
Miscellaneous fixes before 2.0.0 release

### ISSUE THREAD

**Issue by snowman2** [jswhit/pyproj#168]
- [x] Remove docs about radians option in Proj class
- [x] use CRS.from_user_input on itransform

**Comment by snowman2** [comment]
- [ ] update radians option in pyproj.Geod class?

**Comment by snowman2** [comment]
- [ ] #173 
- [ ] #163

**Comment by snowman2** [comment]
@jswhit, thoughts on creating a separate repo for wheel building like https://github.com/sgillies/rasterio-wheels?

Benefits:
- keeps this repo & build process cleaner
- does not take from regular build times
- can add coverage in this repo & without coverage in the other repo

I created an empty one at: https://github.com/pyproj4/pyproj-wheels (pyproj was already taken or I would have used that one for the project name). Or you can create one elsewhere. I can make you an admin if you want to use that one.

**Comment by jswhit** [comment]
@matthew-brett offered to create one for us at https://github.com/MacPython also.  Now he has enabled upload to rackspace from our repo, not sure whether we really need this.  It certainly is simpler to create them from our own repo, and only slows the build time when a release tag is created.    Your other points about code coverage and streamlining the build process are well taken though.

For the 2.0.0 release, I think we are ready.  We can release with only linux wheels and the source tarball for now, and add windows and osx wheels when we get those builds ironed out.

**Comment by snowman2** [comment]
Sounds like a good plan to me. 👍

**Comment by jswhit** [comment]
OK - if I create a release tag now will the linux wheels be created and uploaded to rackspace?

**Comment by matthew-brett** [comment]
I find having a separate wheels repo helps.  For example, what if you have macOS build problems?   At the moment, you'd have to do commits in the main repo to fix those, even if the fixes aren't in the main codebase, but in the build machinery, or tests.   So then you have to do a new release of everything, in order to fix the macOS builds.   I think that's the main reason why most of us do have a separate repo.   I'm happy to authenticate the other (wheel) repo as well if you like.

**Comment by snowman2** [comment]
I agree with @matthew-brett.

And yes, it should push to backspace if you make a new tag.

**Comment by jswhit** [comment]
OK - I'll make a tag and create a new release, then we can move the build stuff to a separate repo at https://github.com/pyproj4/pyproj-wheels.

**Comment by snowman2** [comment]
Uh oh, I forgot about the python "nightly" build. Can you kill that @jswhit?

**Comment by snowman2** [comment]
Looks like it failed to build anyway. Phew!
