### ISSUE TITLE
pip3 install error

### ISSUE THREAD

**Issue by mnewt00** [jswhit/pyproj#178]
Hi, I am getting an error when i try to install pyproj with pip3 on mac. I do have proj installed via brew. I am pretty sure brew doesn't support PROJ.4 so could someone help. Thank you

```iMac:Desktop user$ pip3 install pyproj
Collecting pyproj
  Using cached https://files.pythonhosted.org/packages/53/4b/21643a93e7d33941498087290636e34c6d534aa8baa1ada54cf0d096ffaa/pyproj-2.0.0.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/z1/ky2prf7d6kj1q8rhkldd9zzh0000gp/T/tmp5oq5r0j7:
  ERROR: Minimum supported proj version is 6.0.0.
  
  ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/z1/ky2prf7d6kj1q8rhkldd9zzh0000gp/T/tmp5oq5r0j7" failed with error code 1 in /private/var/folders/z1/ky2prf7d6kj1q8rhkldd9zzh0000gp/T/pip-install-bubud0zl/pyproj`

**Comment by snowman2** [comment]
pyproj 2.0.0 only works with PROJ.4 version 6.0.0. We are working on wheels to simplify the installation. Installation instructions are located at https://jswhit.github.io/pyproj/html/installation.html.

**Comment by snowman2** [comment]
Or you can pin to ~=1.9.5

**Comment by mnewt00** [comment]
Thank you, I did pip3 install pyproj==1.9.6 and it successfully worked

**Comment by snowman2** [comment]
osx wheels are now available for version 2.0.1.

**Comment by swerty24** [comment]
> pyproj 2.0.0 only works with PROJ.4 version 6.0.0. We are working on wheels to simplify the installation. Installation instructions are located at https://jswhit.github.io/pyproj/html/installation.html.

Broken Link

**Comment by snowman2** [comment]
https://pyproj4.github.io/pyproj/stable/installation.html
