### ISSUE TITLE
Test failure on i386

### ISSUE THREAD

**Issue by sebastic** [jswhit/pyproj#181]
The Debian package build for 2.0.1 failed on i386 due to test failures:
```
Trying:
    '%9.3f %11.3f' % (x1,y1)
Expecting:
    '569704.566 4269024.671'
**********************************************************************
File "/<<BUILDDIR>>/python-pyproj-2.0.1+ds/.pybuild/cpython2_2.7_pyproj/build/pyproj/__init__.py", line 454, in pyproj.transform
Failed example:
    '%9.3f %11.3f' % (x1,y1)
Expected:
    '569704.566 4269024.671'
Got:
    '430295.434 -15726905.215'
Trying:
    '%9.3f %11.3f' % (x2,y2)
Expecting:
    '569722.342 4268814.028'
**********************************************************************
File "/<<BUILDDIR>>/python-pyproj-2.0.1+ds/.pybuild/cpython2_2.7_pyproj/build/pyproj/__init__.py", line 456, in pyproj.transform
Failed example:
    '%9.3f %11.3f' % (x2,y2)
Expected:
    '569722.342 4268814.028'
Got:
    '      inf         inf'
Trying:
    '%8.3f %5.3f' % p2(x2,y2,inverse=True)
Expecting:
    ' -92.200 38.567'
**********************************************************************
File "/<<BUILDDIR>>/python-pyproj-2.0.1+ds/.pybuild/cpython2_2.7_pyproj/build/pyproj/__init__.py", line 458, in pyproj.transform
Failed example:
    '%8.3f %5.3f' % p2(x2,y2,inverse=True)
Expected:
    ' -92.200 38.567'
Got:
    '1000000000000000019884624838656.000 1000000000000000019884624838656.000'
...
Trying:
    '%9.3f %9.3f %9.3f %11.3f %11.3f %11.3f' % xy
Expecting:
    '567703.344 351730.944 728553.093 4298200.739 4353698.725 4292319.005'
**********************************************************************
File "/<<BUILDDIR>>/python-pyproj-2.0.1+ds/.pybuild/cpython2_2.7_pyproj/build/pyproj/__init__.py", line 466, in pyproj.transform
Failed example:
    '%9.3f %9.3f %9.3f %11.3f %11.3f %11.3f' % xy
Expected:
    '567703.344 351730.944 728553.093 4298200.739 4353698.725 4292319.005'
Got:
    '432296.656 648269.056 271446.907 -15697729.147 -15642231.161 -15703610.881'
...
Trying:
    '%9.3f %9.3f %9.3f %11.3f %11.3f %11.3f' % xy
Expecting:
    '567721.149 351747.558 728569.133 4297989.112 4353489.645 4292106.305'
**********************************************************************
File "/<<BUILDDIR>>/python-pyproj-2.0.1+ds/.pybuild/cpython2_2.7_pyproj/build/pyproj/__init__.py", line 469, in pyproj.transform
Failed example:
    '%9.3f %9.3f %9.3f %11.3f %11.3f %11.3f' % xy
Expected:
    '567721.149 351747.558 728569.133 4297989.112 4353489.645 4292106.305'
Got:
    '      inf       inf       inf         inf         inf         inf'
...
Trying:
    '%8.3f %8.3f %8.3f %5.3f %5.3f %5.3f' % xy
Expecting:
    ' -92.220  -94.720  -90.370 38.830 39.320 38.750'
**********************************************************************
File "/<<BUILDDIR>>/python-pyproj-2.0.1+ds/.pybuild/cpython2_2.7_pyproj/build/pyproj/__init__.py", line 473, in pyproj.transform
Failed example:
    '%8.3f %8.3f %8.3f %5.3f %5.3f %5.3f' % xy
Expected:
    ' -92.220  -94.720  -90.370 38.830 39.320 38.750'
Got:
    '1000000000000000019884624838656.000 1000000000000000019884624838656.000 1000000000000000019884624838656.000 1000000000000000019884624838656.000 1000000000000000019884624838656.000 1000000000000000019884624838656.000'
```
[Full buildlog](https://buildd.debian.org/status/fetch.php?pkg=python-pyproj&arch=i386&ver=2.0.1%2Bds-1%7Eexp1&stamp=1552243948&raw=0)

**Comment by snowman2** [comment]
It works for i386 on python 3.6 & 3.7. See wheel build logs [here](https://travis-ci.com/pyproj4/pyproj-wheels/builds/103820668).

**Comment by sebastic** [comment]
But not with 2.7 on i686, just like on the Debian buildds.

**Comment by snowman2** [comment]
Definitely correct. Considering that 2.7 will be deprecated Jan. 1, 2020, not super concerning.

**Comment by snowman2** [comment]
What happens if you set PROJ_LIB?

**Comment by snowman2** [comment]
I am thinking that the issue has to with making sure that the pyproj/proj_dir/share/proj directory exists and has the datumgrids. Also, need to set PROJ_WHEEL=true. Are you doing that in the build?

**Comment by snowman2** [comment]
See: https://github.com/pyproj4/pyproj-wheels/blob/master/config.sh

**Comment by snowman2** [comment]
No proj.db errors in the logs. Maybe not then.

**Comment by sebastic** [comment]
Both `PROJ_DIR` & `PROJ_LIB` are set, see: 

 https://salsa.debian.org/debian-gis-team/python-pyproj/blob/debian/2.0.1+ds-1_exp1/debian/rules#L14

The grids from the proj-datumgrid-1.8 archive are available in `/usr/share/proj`.

i386 is known to be problematic due to it's floating point limitations.

`PROJ_WHEEL` is not set, because the package doesn't build wheels.

**Comment by snowman2** [comment]
Okay, sounds like your setup is correct. It is unfortunate that the tests fail.

**Comment by matthew-brett** [comment]
I guess Python 2.7 is going to be around for quite a bit longer than it's official end-of-support date.

i386 users are getting rare on Linux, but I suppose they are a lot more likely to be using Python 2.7.

There are still a lot of 32-bit Windows users out there - do the tests fail there too?

**Comment by snowman2** [comment]
Not sure about 32 bit, but because of the c++ 11 requirements, python 2.7 does not work on windows as the 2008 compiler does not support it.

**Comment by sebastic** [comment]
AppVeyor only tests Python 3.7 on x64.

Since the test for PROJ on i386 also fail, we can probably ignore this issue.

If there are actual users of pyproj on i386 and run into issues, they'll need get PROJ fixed there first.
