### ISSUE TITLE
What happened to the radians flag for transformations?

### ISSUE THREAD

**Issue by andersonjacob** [jswhit/pyproj#185]
My team uses pyproj frequently for conversions to and from ECEF coordinates and we frequently store latitude and longitude as radians.  The 1.9.X versions had a flag for `transform` which would allow us to specify not to convert from degrees to radians.  This has gone from 2.0.  It this something that could be restored or is there a deeper reason for its loss?

**Comment by jswhit** [comment]
I think it's because this change in the C library (version 6.0.0)

https://proj4.org/operations/conversions/unitconvert.html

made it obsolete.

**Comment by snowman2** [comment]
You can convert with:

```python
import math

deg2rad = math.radians(1.)
rad2deg = math.degrees(1.)
```

**Comment by snowman2** [comment]
It uses `proj_angular_input` and `proj_angular_output` to check for radians now:
https://github.com/jswhit/pyproj/blob/9b26e69959ce54e06608351f38d074f319910174/pyproj/_proj.pyx#L330

**Comment by andersonjacob** [comment]
Yes I see those.  I haven't found where `proj_angular_[input|output]` is defined.  Does that know the difference between degree angles and radian angles, or just that the coordinates are angular in nature.  Because if it is the latter and not the former then this won't work with radians.

**Comment by andersonjacob** [comment]
From what I gather from [here](https://proj4.org/development/reference/functions.html#c.proj_angular_input), latter is true so you will always convert angles in your `_proj.pyx` file between degrees and radians if they are angles regardless of the original units.

**Comment by jswhit** [comment]
I think proj_angular_input is poorly named - looks to me that a truth value means angular input is radians (has nothing to do with angular or not, since as you point out degrees are angular).

**Comment by snowman2** [comment]
I guess this does force lat/lon input/output on these functions. Maybe not desirable for all users.

**Comment by snowman2** [comment]
I designed it based on the `proj` executable functionality. But, I see the use case for radians.

**Comment by snowman2** [comment]
Thoughts on replacing the `radians` flag with a `native_angular_units` flag? or with two flags?
1. `native_angular_units_input`:  Specify that the input is already in the correct units.
    - If true, don't do any unit conversions on the input data.
2. `native_angular_units_output`: Specify to convert the output to radians or leave
    - If true, don't do any unit conversions on output data.

**Comment by jswhit** [comment]
Why can't the `xy_in` and `xy_out` flags be used for this?

**Comment by snowman2** [comment]
Are you referring to the name?

**Comment by jswhit** [comment]
I'm referring to the flags that can be used when defining a projection (https://proj4.org/operations/conversions/unitconvert.html).  You can specify  'xy_in=radians' and 'xy_out=degrees' when creating the proj instances used in transform.

**Comment by andersonjacob** [comment]
`xy_in` and `xy_out` seem to be for a doing unit conversion steps in a proj4 pipeline.  Using the pyproj interfaces how would one define such a pipeline?  It isn't clear to me.  Are `xy_in` and `xy_out` honored as parameters of the two CRS that make up a transformation?  I haven't seen anywhere to suggest that they are.

**Comment by jswhit** [comment]
Looks like you are right - they are not honored as parameters when creating a CRS

**Comment by jswhit** [comment]
Seems like the simplest thing to do is to restore the radians flag?

**Comment by snowman2** [comment]
Actually, I think this might be resolved by not converting the output. That way it is in the native projection.

**Comment by snowman2** [comment]
@andersonjacob, do you have an example you could share?

**Comment by snowman2** [comment]
So, historically, radians was used to denote that the input/output was supposed to be in radians.
In 1.9.6 [here](https://github.com/jswhit/pyproj/blob/fe67be00ea17be09cbe0bbcbc36e9c7004cdb8e5/_proj.pyx#L211) it was used for unit conversion for this behavior. This made sense when PROJ accepted radians for some coordinate systems. However, in PROJ 6.0.0, this seems to have changed. It seems to be more of a latlon based infrastructure.

For example, `+init=epsg:4326` used to require radians. However, now it has switched to the GDAL way of everything being in latitude and longitude.

```
>>> CRS("+init=epsg:4326")
<CRS: +init=epsg:4326 +type=crs>
Name: WGS 84
Ellipsoid:
- semi_major_metre: 6378137.00
- semi_minor_metre: 6356752.31
- inverse_flattening: 298.26
Area of Use:
- name: World
- bounds: (-180.0, -90.0, 180.0, 90.0)
Prime Meridian:
- longitude: 0.0000
- unit_name: degree
- unit_conversion_factor: 0.01745329
Axis Info:
- Longitude[lon] (east) EPSG:9122 (degree)
- Latitude[lat] (north) EPSG:9122 (degree)
```
Even though the core `Proj` functionality still returns radians:
```
>>> pj = Proj("+init=epsg:4214")
>>> pj(116.366, 39.867)
(2.0309698373757215, 0.6958104128925793)
```
The `proj_create_crs_to_crs` used by `transform` uses degrees as it is CRS based:
```
>>> transform(Proj(init="epsg:4214"), pj4, 116.366, 39.867)
(6460805.3172788555, 12184989.909717353)
>>> transform(pj4, Proj(init="epsg:4214"), 6460805.3172788555, 12184989.909717353)
(116.36599999999942, 39.86700000000028)
```

So if `radians` is re-introduced, it should be done so with caution.

**Comment by snowman2** [comment]
After that post, I realized that `proj_angular_[input|output]` is probably not doing anything in transform/itransform.

**Comment by andersonjacob** [comment]
In 1.9.6 we are often doing this type of transformation.

```
>>> WGS84 = pyproj.Proj('+init=EPSG:4326')
>>> ECEF = pyproj.Proj(proj='geocent', ellps='WGS84', datum='WGS84')
>>> pyproj.transform(ECEF, WGS84, -2704026.010, -4253051.810, 3895878.820, radians=True)
(-2.137113493845668, 0.6613203738996222, -20.531156923621893)
```

We are converting from an ECEF coordinate system to the LLA coordinate system.  We use radians, because we are often using the coordinates in trig functions or to approximate derivatives which always work best in radians.  We also often go back the other direction from radian LLA to ECEF.

In the new version we don't have the `radians` option so all of our code breaks with the latest changes.  It isn't that we can't work around it; converting from radian to degrees isn't hard; but I was just curious if there were something deep within the PROJ4 library that necessitated the change in interface.

**Comment by snowman2** [comment]
Thanks for your example and for raising the issue! I added back in the `radians` flag in the code in PR #188 and the example you provides works properly with the change.

**Comment by jswhit** [comment]
PR #188 merged, radians kwarg restored.
