### ISSUE TITLE
Should the src/ folder be a fork of Proj.4's source?

### ISSUE THREAD

**Issue by micahcochran** [jswhit/pyproj#19]
Since Proj.4 is now being managed on [GitHub as of 2015-05-27](https://trac.osgeo.org/proj/), should pyproj/src be setup to be a fork of [proj.4/src](https://github.com/OSGeo/proj.4/tree/master/src)?

Would this help the project's management slightly?

My understanding of git and GitHub are quite limited, so there are could be very good reasons not to do that.

**Comment by jswhit** [comment]
we have at least one patch in our local copy (inverse hammer, I believe) that has not been accepted upstream.

**Comment by micahcochran** [comment]
Is there a current Pull Request to patch PROJ.4's inverse hammer?

**Comment by micahcochran** [comment]
Inverse hammer transform patch was merged into the current github development of proj4, which should be released as version 4.9.3.
