### ISSUE TITLE
getting error after install: "ImportError: No module named pyroj"

### ISSUE THREAD

**Issue by mas-dse-mcyi** [jswhit/pyproj#27]
Any thoughts? I ran the following:

    clone github repo or download source release at http://python.org/pypi/pyproj.
    python setup.py build
    python setup.py install (with sudo if necessary).

To test, run python -c "import pyproj; pyproj.test()"

Thanks!

**Comment by micahcochran** [comment]
Does the error say "ImportError: No module named **pyroj**"  or does it say "ImportError: No module named **pyproj**"?

Did you download the release or clone the repo?  What version of python are you running?

pip is another way to install pyproj.  If you have pip installed,  `pip install pyproj`.

**Comment by mas-dse-mcyi** [comment]
Hi Micah,

Thanks for the response. I think you meant to type another error as the same error is listed twice. After restarting my VM this morning, the test script is working. I think one of the bash.rc files needed to be sourced. Thanks!
