### ISSUE TITLE
Slimming Basemap & New Release

### ISSUE THREAD

**Issue by micahcochran** [jswhit/pyproj#34]
I have a [patch for basemap that makes pyproj (and pyshp) external dependencies](https://github.com/matplotlib/basemap/pull/234).     Two of the tests fail on Python 3.x with pyproj 1.9.4 (or 1.9.3), but those failing tests work in the development version ([details](https://github.com/matplotlib/basemap/pull/234)).  @jswhit in the short term, could you please merge the import sys PR #32 ?

It might be nice to eventually have a new release, 1.9.5?

**Comment by ocefpaf** [comment]
> It might be nice to eventually have a new release, 1.9.5?

:100:

**Comment by micahcochran** [comment]
The basemap patch was merged so the development version now has pyproj as an external dependency.

**Comment by jswhit** [comment]
I think we're ready to make a new release (version 1.9.5) any time.

**Comment by micahcochran** [comment]
Good work @jswhit .  I like the consolidation of setup-proj.py into setup.py.

My first thought about releasing pyproj is the release the inverse hammer transform patch in version 4.9.3, but who knows when that release will occur.   Who knows how long it will be before proj4 4.9.3 is the default install?  On Ubuntu for instance, Xenial which is slated for version 16.04 LTS (long term support) to be released April 2016 with proj4 4.9.2.  I seriously doubt 4.9.3 will make it into that release.

I think it is just better to have a new pyproj release.

**Comment by ocefpaf** [comment]
@jswhit how is the new release status?  Is there something we can help review/implement?

**Comment by jswhit** [comment]
I will create a new release on pypi today.

**Comment by jswhit** [comment]
1.9.5 is now on pypi (github tag v1.9.5rel)

**Comment by ocefpaf** [comment]
Thanks!

**Comment by micahcochran** [comment]
Thanks.
