### ISSUE TITLE
segmentation fault in test run after building without bundled proj sources

### ISSUE THREAD

**Issue by jdkloe** [jswhit/pyproj#43]
I encountered an issue for the case when the pyproj module is build without the bundled proj sources. In this case the test run: python -c 'import pyproj;pyproj.test()'
ends with an ugly segmentation fault.

After some digging around I found that this is caused by the fact that my system (Fedora 23) has proj version 4.9.1 which does not have the inverse function for the hammer projection available. The same happens on Fedora rawhide(24) which has proj version 4.9.2
The segmentation fault happens at the call:
    projlonlatout = pj_inv(projxyin,self.projpj)
on line 204 of the file _proj.pyx
The root cause is the fact that the inverse function is called through a pointer in the self.projpj object, and the cython code does not check if this function pointer is defined or not (actually I don't even know if this is possible inside cython, maybe a little additional c-code is needed to do this).

Anyway, it would be nice if some safety check coul;d be added to pyproj to let it safely run for older external proj versions. Of course the problem will go away when proj 4.9.3 is released, as mentioned in issue #19 but I have no idea when that will happen.

**Comment by jdkloe** [comment]
I have disabled the inverse hammer projection test in the rpm build for fedora, and after this all remaining tests run fine for rawhide (upcoming fedora 24). This one will have proj version 4.9.2
For fedora 23, which has proj version 4.9.1, there are 2 failing tests related to the hammer projection (both for python2 and python3). See the details in this log file:
https://kojipkgs.fedoraproject.org//work/tasks/1374/12551374/build.log
I guess this also is related to the missing inverse hammer in these proj versions.

The output for the failing tests is:
Trying:
    p = Proj(proj='hammer') # hammer proj and inverse
Expecting nothing
**********************************************************************
File "/builddir/build/BUILDROOT/pyproj-1.9.5.1-1.fc23.x86_64/usr/lib64/python3.4/site-packages/pyproj/__init__.py", line 324, in pyproj.Proj.__new__
Failed example:
    p = Proj(proj='hammer') # hammer proj and inverse
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest pyproj.Proj.__new__[20]>", line 1, in <module>
        p = Proj(proj='hammer') # hammer proj and inverse
      File "/builddir/build/BUILDROOT/pyproj-1.9.5.1-1.fc23.x86_64/usr/lib64/python3.4/site-packages/pyproj/__init__.py", line 355, in __new__
        return _proj.Proj.__new__(self, projstring)
      File "_proj.pyx", line 84, in _proj.Proj.__cinit__ (_proj.c:1156)
        raise RuntimeError(pj_strerrno(err))
    RuntimeError: b'major axis or radius = 0 or not given'
Trying:
    x,y = p(-30,40)
Expecting nothing
ok
Trying:
    'x=%12.3f y=%12.3f' % (x,y)
Expecting:
    'x=-2711575.083 y= 4395506.619'
**********************************************************************
File "/builddir/build/BUILDROOT/pyproj-1.9.5.1-1.fc23.x86_64/usr/lib64/python3.4/site-packages/pyproj/__init__.py", line 326, in pyproj.Proj.__new__
Failed example:
    'x=%12.3f y=%12.3f' % (x,y)
Expected:
    'x=-2711575.083 y= 4395506.619'
Got:
    'x=16013975.139 y=19338537.497'

**Comment by micahcochran** [comment]
One option would be to move these inverse hammer tests to unittest and skip it the inverse hammer tests when pyproj.test(skip_inv_hammer=true).

That would allow package maintainers to be able to ensure the rest of the functionality stays in the package.  It would retain the useful unittest.

**Comment by jdkloe** [comment]
Yes, that would be a nice option (if the plan is to move all tests to the unittests anyway).
A more general concern I think is that it seems possible to have undefined inverse projections in proj. I have no detailed knowledge of the proj  source code, but if more projections exist without their inverse, then this may trigger the same problem. First step would be to add unittests for all projections, and their inverse I think.

**Comment by micahcochran** [comment]
It appears 21 projections currently in [PROJ.4 have no inverse function](https://github.com/OSGeo/proj.4/search?utf8=%E2%9C%93&q=%22no+inv%22&type=Code).

I've used unittests to test that bug fixes remain fixed.  Unittest does have the ability to skip test if certain conditions aren't right.

**Comment by jdkloe** [comment]
Yes, and I see devel version of proj has added a check for NULL pointer of P->inv and P->fwd in the source files pj_inv.c and pj_fwd.c. These checks are present in the bundled c-code but not in proj releases 4.9.1 and 4.9.2. This will cause segmentation faults if the pyproj module is build without bundles sources with these proj versions. I just tested, and for example the 'airy' projection also shows this segmentation fault.

**Comment by micahcochran** [comment]
PR #44 was merged, which fixed this issue. The repository no longer has this issue. Closing.
