### ISSUE TITLE
It would be nice to tag earlier releases if it's easy

### ISSUE THREAD

**Issue by tfeb** [jswhit/pyproj#46]
We unfortunately have some code which depends on 1.9.3 (needs to be fixed, obviously), and it took me a while to work out which commit this was.  I think it's f036faeefc6ebb15742dc6471642cbe61fe1984b, but I'm not completely sure.

I guess all these got lost when it moved from ?google code?, but if it was easy to tag them that would be cool.

**Comment by micahcochran** [comment]
The 1.9.3 release was on here until the 1.9.5 release.  Are you having issues because there is no longer a 1.9.3 release of pyproj on github?  

Is this an open source project or proprietary one?

**Comment by tfeb** [comment]
I'm trying to get some code to run on a new set of machines.  It depends on pyproj, and the version installed on the donor platform is 1.9.3 (at least `pyproj.__version__` thinks so).  On the new set of machines I'm using conda to construct an environment, and conda only has 1.9.4 (or perhaps 1.9.5).  The code's unit tests are failing for this version so I want to temporarily go back to 1.9.3 before I fix them (basically so I can fix the other failures), which I'm doing by cloning the git repo and then trying to work out which commit 1.9.3 was.  I'd like not to have to guess that last bit: more generally I'd like to be able, if I have something which claims to depend on vx.y of anything, to be able to reliably find vx.y, even if I have tor rebuild it myself.

(The code is a UK Met Office tool to convert climate model output to netCDF: it's BSD licensed.)

**Comment by micahcochran** [comment]
[The tar.gz for 1.9.3 seems to still be on pypi](https://www.versioneye.com/python/pyproj/1.9.3) even if it isn't listed on the website.  Just glancing at the archive it looks like the Changelog might have been one of the last files modified on 2013-01-12 at 10:45.

**Comment by tfeb** [comment]
That doesn't give me much confidence but, well, never mind.
