### ISSUE TITLE
IronPython Compatibility

### ISSUE THREAD

**Issue by m11s** [jswhit/pyproj#52]
Could the pyproj library be used within Ironpython? and are there any additional supporting materials required to do so?

**Comment by micahcochran** [comment]
I don't know.  If IronPython supports C code that Cython generates and calling the underlying PROJ.4  C library, there may be hope for support.  What message does it give when you try to install pyproj under IronPython?

**Comment by m11s** [comment]
Now I just get   Import Error: No module named setuptools
I also remember setuptools having problems in ipy with getframe vs fullframe too.

**Comment by micahcochran** [comment]
Too bad, many more packages are using setuptoolsfor their installation.  It is a [currently a recommendation for python package installation](http://python-packaging-user-guide.readthedocs.org/en/latest/current/).

pyproj 1.9.4 does not require setuptools.

Or edit the setup.py, replace `from setuptools import setup, Extension` with `from distutils.core import setup, Extension`.  There probably should be a try/except statement that falls back to distutils.core.  I think it would be easy to do that at this point.  If that helps, do a PR or I can make one for that.  That is if that is this is the only issue.

**Comment by micahcochran** [comment]
Any luck getting pyproj installed on IronPython?

**Comment by micahcochran** [comment]
I don't think anyone else has need for IronPython.  Also, it seems like IronPython is CPython 2.7 compatible.  This counter to the trend of most Python libraries, upgrading to 3.x and ending support for Python 2.7.   I don't see this happening.
