### ISSUE TITLE
Way to get back proj4 string?

### ISSUE THREAD

**Issue by nickeubank** [jswhit/pyproj#77]
Curious: is there a way to get back a proj4 string from a Proj object? Preferably an informative one?

For example, if I passed:

    p = pyproj.Proj('+init=epsg:4326')

is there a way I could get back `"+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"` through something like a method on `p`?

**Comment by micahcochran** [comment]
p.srs is the proj4 initialization string for the Proj object.

You'd need to call proj4 pj_get_def function, which I don't think pyproj uses.

**Comment by nickeubank** [comment]
@micahcochran Thanks! pj_get_def might be interesting to expose at some point, but p.srs will serve my purposes for now.

**Comment by nickeubank** [comment]
@micahcochran Thinking of trying to add that, but don't have a lot of experience importing C functions (I'm familiar with cython as a tool, just usually use it to speed up python code, not to access C libraries). 

It looks like in `_proj.pyx` at line 56, there is an import of the function you're describing (pj_get_def). Would you mind providing some guidance to how I would go about exposing that to the Python api? Would it be sufficient to just write a `def` wrapper in the `_proj.pyx` file and import it in `pyproj/__init__`?

**Comment by micahcochran** [comment]
#78 has been merged.  So I'm closing this.
