### ISSUE TITLE
Initializing Proj objects

### ISSUE THREAD

**Issue by oldtopos** [jswhit/pyproj#80]
Why does 

`pyproj.Proj( "+init=epsg:%d" % ( theEPSG ) ),`

work, while

`theInitString = "epsg:%d" % ( theEPSG )
pyproj.Proj( init=theInitString )`

fails ?  I see an error saying the data for proj cannot be found with the latter form.  I'm running on Ubuntu 14.04

**Comment by georgeouzou** [comment]
I cannot see a problem with this line of code.. What version of pyproj are you using?

**Comment by micahcochran** [comment]
I ran it on Ubuntu 15.10 (using Python 3.4.3).  It seems to work.

Console:
```Python
In [1]: import pyproj

In [2]: theEPSG=4326

In [3]: pyproj.Proj( "+init=epsg:%d" % ( theEPSG ) )
Out[3]: <pyproj.Proj at 0xb686647c>

In [4]: theInitString = "epsg:%d" % ( theEPSG ); pyproj.Proj( init=theInitString )
Out[4]: <pyproj.Proj at 0xb5eac7ac>
```
